### ISSUE TITLE
Improve the way to set drop chance

### ISSUE THREAD

**Issue by dariusmartin** [Slaymd/CaulCrafting#3]
Actual way is really boring. Let's change that in the future ;)

**Comment by dariusmartin** [comment]
[16:57:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ccc' in plugin CaulCrafting v5.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-eadd615-9060bfa]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-eadd615-9060bfa]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-eadd615-9060bfa]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NumberFormatException: For input string: "<0.01-100>"
    at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_121]
    at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_121]
    at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_121]
    at java.lang.Double.valueOf(Unknown Source) ~[?:1.8.0_121]
    at fr.dariusmtn.caulcrafting.commands.CaulCraftingConfigCommandExecutor.onCommand(CaulCraftingConfigCommandExecutor.java:46) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-eadd615-9060bfa]
    ... 15 more

reported by LeVertUp (Meridas) on Discord #
